=== cleancoderocker/nodejskochbuch/06_Datenformate/036/xml/calendar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tk="http://www.nodejskochbuch.de/xml/calendar"
	targetNamespace="http://www.nodejskochbuch.de/xml/calendar"
	elementFormDefault="qualified">
	<element name="calendar">
		<complexType>
			<sequence>
				<element name="owner" type="tk:owner" />
				<element name="appointments" type="tk:appointments" />
			</sequence>
			<attribute name="name" type="string" />
		</complexType>
	</element>
	<complexType name="owner">
		<sequence>
			<element name="name" type="string" />
		</sequence>
	</complexType>
	<complexType name="appointments">
		<sequence>
			<element name="appointment" type="tk:appointment" minOccurs="0" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" />
	</complexType>
	<complexType name="appointment">
		<sequence>
			<element name="description" type="string" />
			<element name="time" type="string" />
			<element name="location" type="string" />
		</sequence>
	</complexType>
</schema>

=== cleancoderocker/nodejskochbuch/06_Datenformate/037/xml/calendar.xml
<?xml version="1.0" encoding="UTF-8"?>
<calendar
	xmlns="http://www.nodejsprofibuch.de/xml/calendar"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nodejsprofibuch.de/xml/calendar calendar.xsd">
	<owner>
		<name>Max Mustermann</name>
	</owner>
	<appointments name="Example calendar">
		<appointment>
			<description>Katze füttern</description>
			<time>8:00</time>
			<location>Küche</location>
		</appointment>
		<appointment>
			<description>Mit Freundin Schuhe einkaufen</description>
			<time>9:00</time>
			<location>Schuhgeschäft</location>
		</appointment>
		<appointment>
			<description>Computer spielen</description>
			<time>20:00</time>
			<location>Am Computer</location>
		</appointment>
	</appointments>
</calendar>
